### ISSUE TITLE
Cannot read packresources

### ISSUE THREAD

**Issue by andfont** [onebeastchris/GeyserPackSync#19]
- No matter what you put it just can't read them.
 - bugeecord - wallfull Waterfall-Bootstrap:1.20-R0.2
 - Geyser versión 2.2.1-SNAPSHOT
 
[20:23:32 ERROR]: java.lang.IllegalArgumentException: ¡El paquete de recursos ModelEngine.zip no es válido y falló al cargar!
[20:23:32 ERROR]:       at org.geysermc.geyser.registry.loader.ResourcePackLoader.readPack(ResourcePackLoader.java:160)
[20:23:32 ERROR]:       at org.geysermc.geyser.registry.loader.ResourcePackLoader.load(ResourcePackLoader.java:102)
[20:23:32 ERROR]:       at org.geysermc.geyser.registry.loader.ResourcePackLoader.load(ResourcePackLoader.java:57)
[20:23:32 ERROR]:       at org.geysermc.geyser.registry.DeferredRegistry.lambda$new$2(DeferredRegistry.java:64)
[20:23:32 ERROR]:       at org.geysermc.geyser.registry.DeferredRegistry.load(DeferredRegistry.java:111)
[20:23:32 ERROR]:       at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:251)
[20:23:32 ERROR]:       at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:222)
[20:23:32 ERROR]:       at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:752)
[20:23:32 ERROR]:       at org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin.postStartup(GeyserBungeePlugin.java:175)
[20:23:32 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[20:23:32 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:23:32 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:23:32 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[20:23:32 ERROR]: Caused by: java.lang.IllegalArgumentException: ModelEngine.zip does not contain a valid pack_manifest.json or manifest.json
[20:23:32 ERROR]:       at org.geysermc.geyser.registry.loader.ResourcePackLoader.readPack(ResourcePackLoader.java:150)
[20:23:32 ERROR]:       ... 12 more

**Comment by onebeastchris** [comment]
It's failing because that isn't a valid Bedrock edition resource pack. GeyserPackSync doesn't load/convert java edition resource packs
